name: CI

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  django-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        run: docker compose up -d --build

      - name: Run mypy
        run: docker compose run django poetry run mypy --config mypy.ini app_name/

      - name: Run isort
        run: docker compose run django poetry run isort app_name/ --check

      - name: Run black
        run: docker compose run django poetry run black app_name/ --check

      - name: Run flake8
        run: docker compose run django poetry run flake8

      - name: Migration test database
        run: docker compose run django poetry run python manage.py migrate

      - name: Run Test
        run: |
          docker compose run django poetry run coverage run manage.py test &&
          docker compose run django poetry run coverage report --fail-under=80
